### ISSUE TITLE
Proper filenames

### ISSUE THREAD

**Issue by volodymyr-kushnir** [DoggyBlack/Binary-Studio-Academy#1]
Hey, @DoggyBlack, do you think it makes sense to **rename your files to something more meaningful**, perhaps use article title as file name? (I know it does makes sense, I just have to make an issue for you (: so you could close it).

**Comment by DoggyBlack** [comment]
But at the task was written that the name of the file could be arbitrary.

2017-05-20 23:13 GMT+03:00 Volodymyr Kushnir <notifications@github.com>:

**Comment by volodymyr-kushnir** [comment]
@DoggyBlack, exactly, it's just a recommendation, so you can close the issue and we're good. You just had no issues in your repository so I thought it would be cool to add one.

**Comment by DoggyBlack** [comment]
Oh, okay, ty.

2017-05-20 23:33 GMT+03:00 Volodymyr Kushnir <notifications@github.com>:
